image: node:10.14.0

pipelines:
  branches:
    master:
      - step:
          name: Installing & Building
          caches:
            - node
          script:
            - mv .npmrc_config .npmrc
            - yarn
            - yarn build
          artifacts:
            - dist/**
      - step:
          name: Publish to NPM
          deployment: production
          script:
            - npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
            - npm version minor -m "Upgrade to %s [skip ci]"
            - git push && git push --tags
            - pipe: atlassian/npm-publish:0.2.0
              variables:
                NPM_TOKEN: $NPM_TOKEN
